import { NextRequest, NextResponse } from "next/server";
import { z } from "zod";
import { getDb, getMealsByDateLite, todayStr } from "@/lib/db";
import { getCurrentUserIdOrDefault } from "@/lib/user-server";
import { uploadMealPhoto } from "@/lib/blob";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";
// DB insert only — no LLM call. Stays well under the platform default
// timeout, so this endpoint always returns a real JSON response.
export const maxDuration = 15;

const SaveSchema = z.object({
  description: z.string().optional(),
  calories: z.number(),
  protein_g: z.number(),
  fat_g: z.number(),
  carbs_g: z.number(),
  items: z.array(z.any()).optional(),
  confidence: z.string().optional(),
  photo_base64: z.string().optional(),
  // Tiny inlineable thumbnail (~5–10 KB JPEG) generated client-side.
  photo_thumb_base64: z.string().optional(),
  photo_ext: z.string().optional(),
  // Optional second photo (e.g. the back of a package, or a second angle).
  photo_base64_2: z.string().optional(),
  photo_thumb_base64_2: z.string().optional(),
  photo_ext_2: z.string().optional(),
  date: z.string().optional(),
});

function mimeForExt(ext: string | undefined): string {
  const cleanExt = (ext || "jpg").replace(/[^a-z0-9]/gi, "").slice(0, 5).toLowerCase() || "jpg";
  return cleanExt === "png" ? "image/png" :
    cleanExt === "webp" ? "image/webp" :
    cleanExt === "gif" ? "image/gif" :
    "image/jpeg";
}

// Full-size photos go to Blob storage (private) — only a short pathname is
// stored in the meals row, instead of a 150-350KB base64 blob that would
// otherwise bloat every page read of that row.
async function uploadPhoto(userId: string, base64: string | undefined, ext: string | undefined): Promise<string | null> {
  if (!base64) return null;
  const mime = mimeForExt(ext);
  const buffer = Buffer.from(base64, "base64");
  return uploadMealPhoto(buffer, mime, `meals/${userId}/${Date.now()}`);
}

// Thumbnails are tiny (~5-10KB) and shown inline for every meal in a list,
// so they stay as base64 in the row — that's cheaper than N extra round
// trips to Blob just to render a day's worth of thumbnails.
function thumbDataUri(base64: string | undefined): string | null {
  return base64 ? `data:image/jpeg;base64,${base64}` : null;
}

export async function GET(req: NextRequest) {
  const userId = await getCurrentUserIdOrDefault();
  const date = new URL(req.url).searchParams.get("date") ?? todayStr();
  const rows = await getMealsByDateLite(userId, date);
  const meals = rows.map((m) => ({
    id: m.id,
    date: m.date,
    description: m.description,
    calories: m.calories,
    protein_g: m.protein_g,
    fat_g: m.fat_g,
    carbs_g: m.carbs_g,
    items_json: m.items_json,
    ai_tip: m.ai_tip,
    confidence: m.confidence,
    created_at: m.created_at,
    photo_thumb: m.photo_thumb,
    photo_path: m.has_photo ? `/api/meals/${m.id}/photo` : null,
    photo_thumb_2: m.photo_thumb_2,
    photo_path_2: m.has_photo_2 ? `/api/meals/${m.id}/photo?n=2` : null,
  }));
  return NextResponse.json({ date, meals });
}

export async function POST(req: NextRequest) {
  const userId = await getCurrentUserIdOrDefault();
  const json = await req.json();
  const parsed = SaveSchema.safeParse(json);
  if (!parsed.success) {
    return NextResponse.json(
      { error: "validation", issues: parsed.error.issues },
      { status: 400 },
    );
  }
  const m = parsed.data;
  const date = m.date ?? todayStr();

  const [photo_path, photo_path_2] = await Promise.all([
    uploadPhoto(userId, m.photo_base64, m.photo_ext),
    uploadPhoto(userId, m.photo_base64_2, m.photo_ext_2),
  ]);
  const photo_thumb = thumbDataUri(m.photo_thumb_base64);
  const photo_thumb_2 = thumbDataUri(m.photo_thumb_base64_2);

  const db = await getDb();
  const ins = await db.execute({
    sql: `INSERT INTO meals (
        user_id, date, photo_path, photo_thumb, photo_path_2, photo_thumb_2, description, calories, protein_g, fat_g, carbs_g, items_json, confidence
      ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
    args: [
      userId,
      date,
      photo_path,
      photo_thumb,
      photo_path_2,
      photo_thumb_2,
      m.description ?? null,
      m.calories,
      m.protein_g,
      m.fat_g,
      m.carbs_g,
      m.items ? JSON.stringify(m.items) : null,
      m.confidence ?? null,
    ],
  });
  const mealId = Number(ins.lastInsertRowid ?? 0);

  // The "next meal" tip is generated by /api/meals/:id/tip after this
  // endpoint returns, so the save itself is just a fast DB insert.
  return NextResponse.json({ ok: true, id: mealId, ai_tip: null });
}
