import { NextRequest, NextResponse } from "next/server";
import { z } from "zod";
import { getDb, getMealsByDateLite, todayStr } from "@/lib/db";
import { getCurrentUserIdOrDefault } from "@/lib/user-server";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";
// DB insert only — no LLM call. Stays well under the platform default
// timeout, so this endpoint always returns a real JSON response.
export const maxDuration = 15;

const SaveSchema = z.object({
  description: z.string().optional(),
  calories: z.number(),
  protein_g: z.number(),
  fat_g: z.number(),
  carbs_g: z.number(),
  items: z.array(z.any()).optional(),
  confidence: z.string().optional(),
  photo_base64: z.string().optional(),
  // Tiny inlineable thumbnail (~5–10 KB JPEG) generated client-side.
  photo_thumb_base64: z.string().optional(),
  photo_ext: z.string().optional(),
  date: z.string().optional(),
});

export async function GET(req: NextRequest) {
  const userId = getCurrentUserIdOrDefault();
  const date = new URL(req.url).searchParams.get("date") ?? todayStr();
  const rows = await getMealsByDateLite(userId, date);
  const meals = rows.map((m) => ({
    id: m.id,
    date: m.date,
    description: m.description,
    calories: m.calories,
    protein_g: m.protein_g,
    fat_g: m.fat_g,
    carbs_g: m.carbs_g,
    items_json: m.items_json,
    ai_tip: m.ai_tip,
    confidence: m.confidence,
    created_at: m.created_at,
    photo_thumb: m.photo_thumb,
    photo_path: m.has_photo ? `/api/meals/${m.id}/photo` : null,
  }));
  return NextResponse.json({ date, meals });
}

export async function POST(req: NextRequest) {
  const userId = getCurrentUserIdOrDefault();
  const json = await req.json();
  const parsed = SaveSchema.safeParse(json);
  if (!parsed.success) {
    return NextResponse.json(
      { error: "validation", issues: parsed.error.issues },
      { status: 400 },
    );
  }
  const m = parsed.data;
  const date = m.date ?? todayStr();

  let photo_path: string | null = null;
  if (m.photo_base64) {
    const ext = (m.photo_ext || "jpg").replace(/[^a-z0-9]/gi, "").slice(0, 5).toLowerCase() || "jpg";
    const mime =
      ext === "png" ? "image/png" :
      ext === "webp" ? "image/webp" :
      ext === "gif" ? "image/gif" :
      "image/jpeg";
    photo_path = `data:${mime};base64,${m.photo_base64}`;
  }
  const photo_thumb: string | null = m.photo_thumb_base64
    ? `data:image/jpeg;base64,${m.photo_thumb_base64}`
    : null;

  const db = await getDb();
  const ins = await db.execute({
    sql: `INSERT INTO meals (
        user_id, date, photo_path, photo_thumb, description, calories, protein_g, fat_g, carbs_g, items_json, confidence
      ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
    args: [
      userId,
      date,
      photo_path,
      photo_thumb,
      m.description ?? null,
      m.calories,
      m.protein_g,
      m.fat_g,
      m.carbs_g,
      m.items ? JSON.stringify(m.items) : null,
      m.confidence ?? null,
    ],
  });
  const mealId = Number(ins.lastInsertRowid ?? 0);

  // The "next meal" tip is generated by /api/meals/:id/tip after this
  // endpoint returns, so the save itself is just a fast DB insert.
  return NextResponse.json({ ok: true, id: mealId, ai_tip: null });
}
